spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: banksys
        url: jdbc:mysql://localhost:3306/banksystem
        password: "123456"
    sql:
        init:
            schema-locations: classpath:db/init.sql
            data-locations: classpath:db/data-init.sql
            mode: always

server:
    address: 127.0.0.1
    port: 8082

